# Generated by Django 5.0.3 on 2025-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_duration', models.FloatField()),
                ('flow_bytes_per_sec', models.FloatField()),
                ('packet_length_variance', models.FloatField()),
                ('bwd_packet_length_mean', models.FloatField()),
                ('fwd_iat_mean', models.FloatField()),
                ('init_win_bytes_forward', models.FloatField()),
                ('subflow_fwd_packets', models.IntegerField()),
                ('prediction', models.CharField(max_length=20)),
                ('threat_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
